import { Inter } from "next/font/google";
import "./globals.css";
import ProviderLayout from "./components/ProviderLayout/ProviderLayout";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AJARA FACTORY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
      <ProviderLayout>
        {children}
      </ProviderLayout>
     
        </body>
    </html>
  );
}
